name: Frontend Deploy to JCloud

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Create .env file
        run: echo "${{ secrets.FRONT_ENV }}" > .env

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Upload dist files to JCloud via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.JCLOUD_HOST }}
          username: ubuntu
          key: ${{ secrets.JCLOUD_SSH_KEY }}
          port: 19072
          source: "dist/*"
          target: "/home/ubuntu/app/frontend/dist/"

      - name: Reload Nginx (optional)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.JCLOUD_HOST }}
          username: ubuntu
          key: ${{ secrets.JCLOUD_SSH_KEY }}
          port: 19072
          script: |
            echo "✅ 프론트 배포 완료: Nginx reload"
            sudo nginx -t && sudo systemctl reload nginx
